### ISSUE TITLE
button visibility issues with multiple tabs

### ISSUE THREAD

**Issue by domino14** [domino14/liwords#102]
1. ragequit
2. open a duplicate tab on the same game (on chrome, middle-click the reload button)
3. go back to the original tab
sometimes the other 4 buttons are disabled, sometimes not

![](https://cdn.discordapp.com/attachments/743518889048277100/763276775257931786/Screenshot_2020-10-07_at_13.49.01.png)

![](https://cdn.discordapp.com/attachments/743518889048277100/763277819986837525/Screenshot_2020-10-07_at_13.51.51.png)

**Comment by atomiccupcake** [comment]
Can you include more information? Did you resign or ragesit and walk away? This keys off whether it's your turn or not... can you get a screenshot including the player cards so I know who's turn it is when you're seeing this?

**Comment by andy-k** [comment]
more info:
1. finish a game (either player can timeout, ragequit, triple-challenge, or complete it normally) so the end-of-game controls (the blue bar and options/export gcg/exit/rematch, streaks) replace the during-game controls (rack and ragequit/pass/challenge/exchange/play)
2. while keeping the ended game's tab open, open a new tab with the same url (on chrome, middle-click or cmd+click the reload button)
3. observe that the original tab reverts to during-game controls, thus unable to rematch

expected: original tab retains the end-of-game controls

**Comment by andy-k** [comment]
no longer reproducible for me
