### ISSUE TITLE
[Request] Add Catalan language

### ISSUE THREAD

**Issue by jmontane** [domino14/liwords#1091]
Hi,
Is liwords multilanguage? I was able to run docker stack locally, all works fine! So, I ask/request for adding new languages. I mean: tile distribution, dictionary, and translating UI.

I play word games in Catalan language, and I keep updated an open-source Catalan wordlist. So, can provide linguistic resources for Catalan languages.

**Comment by domino14** [comment]
Yep, we can support any language/tile set (we have Norwegian and German
too), but localizing the UI is a little bit harder, and we haven’t made it
localizable yet. IIRC Catalan has two-letter tiles which might make it a
little more difficult but it’s doable.

Is the open-source Catalan wordlist the same one used as in competition? If
you think we could get players to play in Catalan on Woogles let me know.

**Comment by jmontane** [comment]
Yep, Catalan tiles distribution has special tiles (non-ASCII and multiletter ones): Ç, NY, and L·L. Additionally, Q tile is played as QU in all tournaments.

[DISC](http://diccionari.totescrable.cat/versio/DISC2-LP.zip) (utf8 encoded) is open-licensed Catalan wordlist. DISC is used as arbitration wordlist in some tournaments. But, some other tournaments use another closed wordlist. Yes, we (Catalan players) are divided with 2 list of words.

We play an [informal online competition](http://www.ajuscrabble.cat/apalabrados/campionats/) with a scrabble-like app called [Apalabrados / Word Crack](https://www.apalabrados.com/en-US), but we are searching alternatives to such app. It exists a dedicated Catalan website, called [Catamots](https://catamots.cat/), but it uses the closed wordlist, and it's web 1.0 styled. So, yes! Woogles is a really good option for us! I think some players (~80) could use Woogles to play in Catalan language regularly.

In the past, I helped to adapt and translate Scrabble3D, Quackle, Elise, and Xwords to Catalan. So I can translate Woogle for free too.

**Comment by domino14** [comment]
quick question - since the Q tile is played as QU, then bingos (plays that use all 7 tiles) must be at least 8 letters long?

**Comment by jmontane** [comment]
In Catalan we distinguish letter from tiles:

- Bingos are done always with a 7-tiles move.
- There are tiles with 1 (A-Z,Ç), 2 (NY or QU) and 3 characters  (L·L) long!

So, *theoretically*:
- A 7 tiles rack could be 4*1+2*2+1*3=11 chars long.
- A 7 tiles move (blanks played as 3 letter tile) could be 2*1+2*2+3*3=15 chars long

Of course, there are words of 15 tiles length in dictionary. Currently, longest words are 18 chars long.

About QU tile:
There are two possible solutions about this issue:
Replace Q tiles with a 2-letter QU tile. This one is preferred by me.
Use a Q single-letter tile and remove U preceding Q at dictionary side. Just a simple hack

**Comment by domino14** [comment]
The PR will probably be titled "Més que un app"

**Comment by jmontane** [comment]
As this issue derived to adding Catalan language support to Woogles, I've edited issue title :)

Just "one more thing". Can a "slow mode" be added? Something like 7 days/turn. It would allow plays in asynchronous mode, like old postal mail chess games.

**Comment by domino14** [comment]
we've had a slow mode in mind for a long time. It will likely be developed, just a matter of time.

**Comment by Naushika322** [comment]
Hola César. Me llamo Sayaka, soy jugadora de Scrabble en Catalan, Español e Inglés. Hace unos años fui la presidenta de la Federación de Scrabble en Catalan, pero ahora estoy apoyando a otra asociación que se llama AJUSC (Asociación de jugadores de Scrabble en Catalan).
Hace casi dos semanas que mi compañero de Scrabble en Catalan, Joan, os preguntó si podríais añadir el catalan al Woogles o no. Veo que la conversación terminó aquí y no hemos recibido vuestra respuesta.
El mundo del Scrabble en Catalan está dividido en dos por la diferencia de ideas y de diccionario, igual que en los Estados Unidos con CoCo, Naspa y WGPO. La Federación tiene su propia APP que se llama “Catamots”, como la “REdeletras” de la FISE, del Scrabble en Español, pero nosotros, la Ajusc, estábamos buscando una nueva plataforma y nos ha gustado mucho vuestro Woodles. ¿Qué opinais? ¿Pensáis que no merece la pena toda la faena de hacer los dígrafos para pocos jugadores? Es decir, ¿no es factible añadir el Catalan? Nosotros organizamos cada año el mundial de Scrabble en Catalan y otros torneos de Scrabble competitivo. ¿Hay alguna cifra mínima de jugadores que tenemos que tener?

**Comment by domino14** [comment]
Hola @Naushika322. Es totalmente factible, y creo que sí se puede hacer. Todo es cuestión de tiempo. De todos modos, sí he investigado que es lo que se puede hacer, y creo que no va a ser tan difícil añadir el Catalán. Joan me dijo que tal vez podrían jugar mas o menos como 80 personas, que sería bien bueno. Piensas que la cifra es fiel? Déjame ver si puedo prioritizar esta adición tal vez en el próximo mes o dos. Nos mantenemos en contacto.

**Comment by Naushika322** [comment]
En la liga que organiza la Ajusc dos veces al año se apuntan más o menos 90 personas, pero no toda la gente se apuntará al Woogles. Pero tengo más ideas como por ejemplo torneos interclubes o algo así. Haremos todo lo que podamos para la difusión del Woogles. Muchas gracias. Estaremos en contacto.

**Comment by domino14** [comment]
@jmontane @Naushika322 
Are there single characters that you prefer to type in for the special digraph tiles? 

On Woogles you can type in your play into the board. Typing in L•L is probably unwieldy - even if it will display properly, it is not simple to take in multi-character input with the keyboard.

I was thinking you can type in "W" for L.L and "Y" for NY (or perhaps Ñ?) Q for QU seems fine too. Would those be good? Or do you have other preferences?

**Comment by jmontane** [comment]
Hi!

Words with K, Y (not following N), and W letters are forbidden currently, so using W for L·L, Y for NY, and Q for QU is fine (same mapping was used in the past for Wabble and customized build of Quackle)

In long term future, maybe words with K, Y and W letters could be played using a blank. So, this mapping could be revisited. But I think it's the natural and expected choice now.

**Comment by domino14** [comment]
this is coming soon (within the next few days). I will notify you all here. Let me know how else we can get the word out?

**Comment by Naushika322** [comment]
Do you mean that you have finished?

**Comment by domino14** [comment]
Yes, pretty much. I still have to do some testing but it should be live on
Woogles in a couple of days.

**Comment by Naushika322** [comment]
I'm in Woogles group on Facebook, so if you post something in it, I can
share it. And Catalan Scrabble Associatión also has an account on Facebook,
so I think they can do the same.
And you can post something on Twitter, too.

Thank you so much, César and Woogles team!

Sayaka
