### ISSUE TITLE
Puzzle not allowed to exchange tiles

### ISSUE THREAD

**Issue by ddugovic** [domino14/liwords#1112]
I attempt to submit "EXCH BH" as my answer to https://woogles.io/puzzle/HuZaS4oEmov4ooY3YcWxFP
![image](https://user-images.githubusercontent.com/1834123/215349120-36150e64-d6b7-400d-994e-36dc8864c9ef.png)
![image](https://user-images.githubusercontent.com/1834123/215349156-4869e194-04f1-49d2-b251-657a723637dd.png)

I click "Exchange", however my answer is not responded to:
![image](https://user-images.githubusercontent.com/1834123/215349120-36150e64-d6b7-400d-994e-36dc8864c9ef.png)

**Comment by domino14** [comment]
thanks nd
