### ISSUE TITLE
Triple Challenge is not rated at all (sometimes)

### ISSUE THREAD

**Issue by jvc56** [domino14/liwords#112]
The alledged game:

https://woogles.io/game/AaWn7ECKoH2QfqquKD3jYk
https://woogles.io/game/j4zK9FUsTGE8VNxv8xU4Ng

**Comment by domino14** [comment]
ALLEGED aren't you a scrabbler

**Comment by jvc56** [comment]
ALLEDGED# !!! HIT THE BOOKS YOU NOOOB
