### ISSUE TITLE
blanks count as consonants

### ISSUE THREAD

**Issue by andy-k** [domino14/liwords#1153]
<img width="368" alt="image" src="https://user-images.githubusercontent.com/4179698/226799419-13cee2e9-14f5-4fbc-82ac-2b727e228653.png">

since https://github.com/domino14/liwords/commit/2652bfd7f3787caa49177197b143f0e0820d1918#diff-6359dd67c76ec497d992b3c558d61a2002897f8fd756590537412900c11e322eL11

**Comment by domino14** [comment]
fixed by #1168
