### ISSUE TITLE
safari broken on local dev

### ISSUE THREAD

**Issue by domino14** [domino14/liwords#133]

**Comment by domino14** [comment]
![](https://cdn.discordapp.com/attachments/749448674861514813/765928258507243571/Screenshot_2020-10-14_at_21.23.58.png)

![](https://cdn.discordapp.com/attachments/749448674861514813/765928270814117938/Screenshot_2020-10-14_at_21.24.09.png)


![](https://cdn.discordapp.com/attachments/749448674861514813/765928282549125120/Screenshot_2020-10-14_at_21.24.19.png)

**Comment by atomiccupcake** [comment]
This is actually the same as 114. We need to wrap playing the sounds in a try/catch.
