### ISSUE TITLE
enhance `game-accepted` messages with some extra data

### ISSUE THREAD

**Issue by magratheazaphod** [domino14/liwords#150]
I'd like these messages to contain two extra fields: 1) the lexicon, and 2) a description of the time setting (Ultra-Blitz, Blitz, Rapid Regular). This will allow me to set up some extra Cloudwatch dashboards that track our distribution of games between these categories.

**Comment by domino14** [comment]
We also want to log total number of games played, perhaps once every hour or so. Anything else @magratheazaphod ?
