### ISSUE TITLE
Creating a blank out of thin air, possibly via the premove feature

### ISSUE THREAD

**Issue by magratheazaphod** [domino14/liwords#153]
School Scrabble Player reported [in our Discord](https://discordapp.com/channels/741321677828522035/764339046108889119/766388795875655711) that he was somehow able to create a blank out of thin air in [this game](https://woogles.io/game/cN4LLEE3). We think it has something to do with putting a premove on the board at a spot where opponent ended up playing.

**Comment by jvc56** [comment]
I think it's definitely when a move comes down over a premove. A similar thing happened to me where one of my tiles disappears. It's always when an opponent plays over my premove.

**Comment by domino14** [comment]
@jvc56 were you typing? we were thinking it was related to using drag-drop

**Comment by jvc56** [comment]
I was typing, yeah, I never drag and drop.

**Comment by domino14** [comment]
Thanks to a couple of players who were able to reproduce this reliably:

- start a game against someone
- premove somewhere, when it is NOT your turn, then click and HOLD one of the tiles you premoved. For example, let's say you're clicking and holding a tile at 8K.
- if your opponent makes a play that has a tile at 8K, then you will suddenly get a blank -- the blank modal will pop up. You can assign the blank or dismiss it and then the blank will be on your rack
- thankfully, the blank is not real. You can't play it or use it in any way.

**Comment by domino14** [comment]
fixed by #172
