### ISSUE TITLE
memory leak, app crashed

### ISSUE THREAD

**Issue by domino14** [domino14/liwords#220]
App crashed at 16:59:41 EDT on Oct 29 with an out of memory error. Memory has been slowly increasing for the last 6 days. It held steady at 80% for 1-2 days and then rapidly jumped up to 100 over the course of the 3 minutes prior to 5 pm.

We think there is a memory leak and/or goroutine leak.
<img width="1447" alt="Screen Shot 2020-10-29 at 5 03 10 PM" src="https://user-images.githubusercontent.com/585318/97663584-60e10e80-1a50-11eb-9237-4b25fd369d22.png">

**Comment by jvc56** [comment]
Could not reproduce the bug locally. Memory profiling added to master (yes I know that's not kosher hopefully we can remove it relatively quickly).

**Comment by domino14** [comment]
It is highly likely that this is caused by a combination of two things:

- Rematches load the game into cache again to fetch the GameRequest:

```go
		// XXX: rewrite to call the less expensive GetMetadata.
		g, err := b.gameStore.Get(ctx, gameID)
		if err != nil {
			return nil, "", err
		}
```
I should follow my own note there to rewrite this

- Revisiting a game loads it back into the cache.

Although a regular game ending should unload the game from the cache, in both of the above cases, the cache is not emptied again. The game cache has a size of 4K. We will decrease the size to 400, and estimate using the heap debug endpoint approximately how much space a game takes up. Then we can set a sane size for this cache, and fix the two issues above to not load the entire game object again if not needed.

**Comment by domino14** [comment]
memory has been perfectly flat for the last two days at around 25%
