### ISSUE TITLE
Abort game with mutual consent

### ISSUE THREAD

**Issue by domino14** [domino14/liwords#291]
There are times when a game needs to be aborted. We don't necessarily have to support adjournment, but situations like matching the wrong person, playing with the wrong settings, or having an emergency. We should support aborting a game (with consent of the opponent).

**Comment by ddugovic** [comment]
> Jan 1st - 6:56 PM
> greenteaIf you open with a play and then the opponent doesn't play, it would be nice to have an abandon option that doesn't affect rating.
