### ISSUE TITLE
crazy display glitch with tiles showing three letters on them?

### ISSUE THREAD

**Issue by domino14** [domino14/liwords#307]
![image (2)](https://user-images.githubusercontent.com/585318/102160151-e1b66700-3e52-11eb-88a1-8038ca385ee5.png)
See the tiles on the right hand side. They're supposed to be a Z and a Y.

**Comment by domino14** [comment]
Some other things screwed up with this: the As in the pool are not all caps (and one has a caret). Last opponent's move is `By` instead of QUa, lowercase O in pool.

**Comment by domino14** [comment]
I think this is due to a Chrome plugin.

**Comment by andy-k** [comment]
i just noticed the translator icon on the address bar (leftmost icon at the right). it's built in, not a plugin.

the user should choose "never translate this site": https://www.howtogeek.com/407924/how-to-turn-translation-on-or-off-in-chrome/
