### ISSUE TITLE
Set keyboard focus on Opponent field when creating a new game

### ISSUE THREAD

**Issue by RodneyWeis** [domino14/liwords#448]
When creating a new club game / friend game, it would be nice to have the keyboard focus on the opponent / friend name field in the modal automatically, instead of having to click on the field.

**Comment by RodneyWeis** [comment]
I'd like to try this one to get used to navigating the codebase.

**Comment by domino14** [comment]
@RodneyWeis sounds like a good starting project :)

**Comment by RodneyWeis** [comment]
> @RodneyWeis sounds like a good starting project :)

Precisely my intention, @domino14  :)
I don't know how much attention you give to grooming the backlog, but I'm happy to work on this one if you'd like to assign it
