### ISSUE TITLE
TypeScript error in /opt/liwords-ui/src/gameroom/table.tsx

### ISSUE THREAD

**Issue by ddugovic** [domino14/liwords#450]
![image](https://user-images.githubusercontent.com/1834123/110297939-96c37000-7fb9-11eb-883f-e10061d5d254.png)

Looks similar to https://github.com/ant-design/ant-design/pull/26864

Attempted to fix via `docker-compose pull && docker-compose up -d`

```
/opt/liwords-ui/src/gameroom/table.tsx
TypeScript error in /opt/liwords-ui/src/gameroom/table.tsx(290,23):
Expected 0 arguments, but got 1.  TS2554

    288 |     return () => {
    289 |       setGameInfo(defaultGameInfo);
  > 290 |       message.destroy('board-messages');
        |                       ^
    291 |     };
    292 |     // React Hook useEffect has missing dependencies: 'setGameEndMessage' and 'setPoolFormat'.
    293 |     // eslint-disable-next-line react-hooks/exhaustive-deps
```

Browser version:
![image](https://user-images.githubusercontent.com/1834123/110298209-f6ba1680-7fb9-11eb-8ec2-b630d014b5ff.png)

**Comment by andy-k** [comment]
i can't reproduce this because `liwords-ui/package.json` already specifies a version of antd that should already include the fix

**Comment by ddugovic** [comment]
OK, how do I deploy that latest image?

I attempted to fix this via `docker-compose pull && docker-compose up -d`.

**Comment by andy-k** [comment]
maybe try something like `docker-compose build --pull --no-cache frontend`

**Comment by ddugovic** [comment]
OK, I'll study some of this Docker stuff...

```
Step 9/9 : CMD ["npm", "start"]
 ---> Running in 35d262e0e0e7
Removing intermediate container 35d262e0e0e7
 ---> 28ad484dba97
Successfully built 28ad484dba97
Successfully tagged liwords_frontend:latest
➜  liwords git:(master) ✗ cat build.sh
#!/bin/bash
git fetch -p && git pull && git submodule update --init --recursive && \
#docker-compose build --pull --no-cache frontend
docker-compose pull && docker-compose up -d
➜  liwords git:(master) ✗ docker run liwords_frontend:latest

> liwords-ui@0.1.0 start /opt/liwords-ui
> react-scripts start

Could not find a required file.
  Name: index.html
  Searched in: /opt/liwords-ui/public
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! liwords-ui@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the liwords-ui@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-08T13_14_11_205Z-debug.log
```

**Comment by andy-k** [comment]
after building, try `docker-compose up -d frontend` (`docker-compose.yml` specifies some volume mounts that the Dockerfile `docker run` won't pick up)

**Comment by ddugovic** [comment]
Yeah, all these suggestions are logical, and it makes sense that if I could only deploy the correct dependencies, things should function correctly.  Sadly I continue observing the same error even after rebuilding and deploying the front end.

**Comment by ddugovic** [comment]
Thanks, I must have previously tried to build this.  That solution worked.

(Previously I used `git status` to attempt to verify that I have no local changes.)
