### ISSUE TITLE
Need endpoint that returns moderators and admins

### ISSUE THREAD

**Issue by atomiccupcake** [domino14/liwords#513]
So that we can tag people in the UX. Similar in format and functionality to the "GetFullBlocks" endpoint.

Response format:

{
  admin_user_ids: [],
  mod_user_ids: [],
}

**Comment by magratheazaphod** [comment]
some additional factors on the engineering implementation:
* These look like SELECT * queries from our user database. However, if we do this the naive way, we'll get 1000s of queries an hour, which is bad.
* Therefore, we want some kind of caching layer that updates who admins/mods are periodically.

**Comment by domino14** [comment]
We ended up using queries with indices, and caching on the frontend. I think this is fast enough.

@atomiccupcake  you can test with 

```
curl -v 'http://liwords.localhost/twirp/user_service.SocializeService/GetModList' \
  -H 'Content-type: application/json' -d '{}'
```
