### ISSUE TITLE
Need more information in chat message

### ISSUE THREAD

**Issue by atomiccupcake** [domino14/liwords#515]
To implement the UX, we need more information in the messages:

Current response:
{
  channel: "chat.tournament.dallasbedford"
  id: "1618534097639-0"
  message: "Okay Caesar, you initiate"
  timestamp: 1618534097639
  userId: "Eb67dVRHCQVmiKsYxbXZbi"
  username: "afeicher"
}

Proposed response:
{
  country_code: "us"
  avatar_url: "https://...."
  channel: "chat.tournament.dallasbedford"
  id: "1618534097639-0"
  message: "Okay Caesar, you initiate"
  timestamp: 1618534097639
  userId: "Eb67dVRHCQVmiKsYxbXZbi"
  username: "afeicher"
}

**Comment by atomiccupcake** [comment]
Current handler for MessageType.CHAT_MESSAGE starts on like 382 of socket_handler.ts

**Comment by domino14** [comment]
@atomiccupcake Every chat message now has an avatar_url and a country_code, whether it comes from the socket or through XHR. Thank you @andy-k!
