### ISSUE TITLE
Need database record and endpoints for friends

### ISSUE THREAD

**Issue by atomiccupcake** [domino14/liwords#516]
This should work almost exactly like blocks.

Please make a table for keeping track of friends.
Make an endpoint that returns the friends you have selected.

Response body:
{
  friendsList:
    [
      {
         user_id: "dztWVeEgY8f9k4DP6oy6MF", 
        username: "Lola",
        avatar_url: "https://...",
        country_code: "us",
     } ,
  ],
}

Make an endpoint for adding a friend. Request body:
   {user_id: "dztWVeEgY8f9k4DP6oy6MF"} 
Make an endpoint for removing a friend. request body:
  {user_id: "dztWVeEgY8f9k4DP6oy6MF"}

**Comment by domino14** [comment]
@atomiccupcake - this was implemented by Andy. See description of this PR:

https://github.com/domino14/liwords/pull/525

The API is very similar to that of blocks. We don't have avatar/country code in the response yet. This will likely come in another PR.
