### ISSUE TITLE
Define Scrubbing Cases

### ISSUE THREAD

**Issue by jvc56** [domino14/liwords#522]
Player A is suspended. Player B (who is not suspended) has played player A recently. Player M is a mod. Player U is any arbitrary user who is not a mod or admin
There are six different "views" we consider (three for player U and three for player M)
• Either player M or player U is viewing:
   ◦ Player A's profile page
   ◦ Player B's game history (in Player B's profile), which has a game against player A
   ◦ The game the Player A and Player B played
In which scenarios should we completely erase all of player A's personal information?
If we censor player A's profile page in any case, should we treat the resulting profile page the same as a nonexistent user, or do we acknowledge that player A's account exists on Woogles?
Should any of the above scenarios depend on whether player A is temporarily or permanently suspended?

**Comment by dacronbb** [comment]
I see it as a suspended versus banned/deleted:

**if suspended:**
- show things as normal, but obviously abilities to interact with this person are disabled
- not sure we need to show anything like "this account has been suspended"

**if banned or user deleted account**
- treat as nonexistent user (generic avatar, generic string)
- profile pages would have some sort of empty state

does this sound reasonable? i can mock some stuff up today if so

**Comment by jvc56** [comment]
Yes, this sounds reasonable.

Right now deleted accounts have "[deactivated]" as the generic string (for use in other player's games and game histories). We will also need a generic avatar, either an image in the public domain or something we make ourselves. A nonexistent user page mock would also be useful who for real don't actually exist (like if you mistyped the URL).

**Comment by dacronbb** [comment]
makes sense! thx!

**Comment by dacronbb** [comment]
I think we can use the same for bant/deactivated/nonexistent.

[Here are some thoughts](https://www.figma.com/file/XTG9fsH9UO8pSBTHNuUsBD/Woogles-for-Engineering?node-id=4756%3A3).

I know some of this hasn't been built - you can use the same ? image and text for whatever we have now.

We also might consider a search box in the future.

**Comment by jvc56** [comment]
These look good to me!
