### ISSUE TITLE
macondo avatar

### ISSUE THREAD

**Issue by andy-k** [domino14/liwords#542]
related to #536 

currently https://woogles-prod-assets.s3.amazonaws.com/macondog.png is 199,920 bytes, 1000x1000 png.

here's my attempt at `macondosmoldog.png`, less than 4kB.

![macondosmoldog](https://user-images.githubusercontent.com/4179698/115518030-57778700-a2ba-11eb-9b8f-c034f1e09063.png)

**Comment by atomiccupcake** [comment]
Replaced in prod. Thanks!
