### ISSUE TITLE
Sentence case vs Title Case

### ISSUE THREAD

**Issue by andy-k** [domino14/liwords#557]
to improve consistency, i suggest to change these labels to Sentence case (i prefer Sentence case to Title Case):
- "Log In" button in the Log In modal
- in Settings/Personal info, the sidebar is "Personal Info" (but the title is "Personal info")
  - that page has a button labeled "Add a Profile photo"
  - the bio Tips has a "See Full Guide" button
- in Settings/Change password, the sidebar is "Change Password" (but the title is "Change password")
  - that page has fields labeled "Old Password" and "New Password"
    - the forgot password page has a field labeled "Email Address"
- in Settings/Secret features, the title is "Secret Features" (but the sidebar is "Secret features")
  - that page has a link called "Learn More."
- the top right menu has "View Profile" (and has "Log out")
- in Profile page, "Game History" (but "Edit settings")
- "Help Chat", "All Chats" (but "Show list", "Start new chat")
- "View Profile" option when clicking username in chat
- "Play a Computer"/"Match a Friend"/"Create a Game"/(club "Send Match Request") modal titles
  - "Initial Minutes", "Time Setting", "Use Max Overtime", "Use Increment", "Create Game" (but "Challenge rule")
- "Available Games", "Games Live Now", (club "Recent Games") in the middle column
- in game, "View Profile" links next to player ratings near score/time
  - in the pool view, Rearrange has a "Vowels First" option
- "Meet the Team" in About page

**Comment by domino14** [comment]
Verified that these should all be in `Sentence case` - anything not in Sentence case should be changed.

**Comment by ddugovic** [comment]
To me any `<h[1-6]>` heading sounds like a title, but anyway I can do this.
![image](https://user-images.githubusercontent.com/1834123/117456835-42cbfd80-af0e-11eb-8fd4-012288302dc6.png)
