### ISSUE TITLE
tournament dropdown z-index

### ISSUE THREAD

**Issue by domino14** [domino14/liwords#572]
<img width="503" alt="Screen Shot 2021-04-30 at 12 42 23 AM" src="https://user-images.githubusercontent.com/585318/116649311-010ae800-a94d-11eb-8b6d-86e1e4f2b8af.png">

**Comment by atomiccupcake** [comment]
Need to fix another way dropdown menus are all attached to the root, just like modals. So #575 broke the seek modal
