### ISSUE TITLE
Got error on production when clicking on my chats list in the lobby

### ISSUE THREAD

**Issue by domino14** [domino14/liwords#576]
Someone sent me a match request, I went to All Chats to talk to him, and the screen turned dark

<img width="1527" alt="Screen Shot 2021-05-01 at 9 23 55 PM" src="https://user-images.githubusercontent.com/585318/116799035-89ab9480-aac3-11eb-9033-330a1b80e67a.png">
<img width="991" alt="Screen Shot 2021-05-01 at 9 24 07 PM" src="https://user-images.githubusercontent.com/585318/116799040-903a0c00-aac3-11eb-961d-7613abaf56e2.png">

**Comment by domino14** [comment]
Seemingly can replicate after clicking all chats, send a message to someone, then click All chats again to go back to the chat list

**Comment by domino14** [comment]
<img width="870" alt="Screen Shot 2021-05-01 at 9 26 07 PM" src="https://user-images.githubusercontent.com/585318/116799077-d7c09800-aac3-11eb-8c9c-22618c926b7c.png">

the "replicate" above is actually a different error, see screenshot

**Comment by andy-k** [comment]
root cause: `useBriefProfile` called in a loop: https://github.com/domino14/liwords/pull/550/files#diff-a445470f87d50cc919125c66843d5c44391a504b7c94ba48d25f4ed5de248cbcR236
