### ISSUE TITLE
new tournament issues

### ISSUE THREAD

**Issue by domino14** [domino14/liwords#610]
issues:

- nwl20 was 20 instead of 7 minutes (i set them up with the same dialog)
- a game failed to start
- going back to the tournament does not show WATCH buttons for ongoing games
- beginning state was weird when i was the director and playing (no good luck in your game)
- opening in different window doesn't show the status bar widget properly
- starting game 4: 
     Thanks for registering for the Woogles Testing Funfest 2.
     (for both me and bnjy)
- jellomochas "sometimes my "I'm ready" would cancel itself for no reason"
   Nattapat: I think it cancels when another game starts

Thoughts (in order):

- probably something with the state of the antdesign widget, or I just made a misclick. There's no feedback in the director tools after the fact yet
- This is a known problem and seems to happen to people with poor connections. I am not sure if it happens more with tournaments. The tournament fixes itself as it lets people try again.
- (Race condition)
- (Race condition?)
- (Race condition?)
- (Race condition?)
- Probably a reducer bug

`(Race condition)` refers to a certain race condition that probably triggered all these bugs. When you get the `ONGOING_GAMES` message from the socket it shows up before we know the tournament ID from the backend (getTournamentMetadata doesn't execute until later) and thus it gets sent to the wrong reducer. See:
https://github.com/domino14/liwords/blob/master/liwords-ui/src/store/socket_handlers.ts#L761-L779

**Comment by Jayem2k20** [comment]
I ran a small tournament (4 player, 3 x 15 minute, CSW19 round robin) last night, but I didn't play.
Using the latest version of Chrome for Windows, everything seemed to go okay from my (the Director's) viewpoint. The watch buttons were always visible, even after observing a game and then leaving.
One player did report that at the end of her 2nd game, her screen was "Jumbled" and she couldn't do anything other than close her browser and rejoin. Her game had finished before this happened and closing her browser fixed the problem and she was able to continue. without any further problems. No sign of anything untoward in the log files, and I wasn't able to reproduce the issue.
Apart from that, everything ran perfectly. Great job guys!
