### ISSUE TITLE
Add birthday info to sign-up

### ISSUE THREAD

**Issue by dacronbb** [domino14/liwords#627]
[see figma mock](https://www.figma.com/file/XTG9fsH9UO8pSBTHNuUsBD/Woogles-for-Engineering?node-id=4712%3A5625)

**Comment by andy-k** [comment]
@dacronbb for a more inclusive experience please consider
- y-m-d (instead of m-d-y)
- [having Full Name instead of First+Last](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/)

**Comment by Jayem2k20** [comment]
It seems counter-intuitive to enter a date as YYYY-MM-DD. I've tweaked the code on the Personal info page to ask for it in the format DD-MM-YYYY (I'm in the UK). It still saves it to the DB as YYYY-MM-DD

**Comment by andy-k** [comment]
i brought it up because _personally_ i find asking for m-d-y _offensive_ to people who aren't using that sequence such as myself. it seems y-m-d would be most acceptable to both m-d-y and d-m-y users.

(the problem with an input textbox asking for dd-mm-yyyy in the uk version is, when someone who's born in the first twelve days of a month keys in mm-dd-yyyy, that would go unnoticed; using three fields avoids this if the month dropdowns show names instead of numbers.)

**Comment by Jayem2k20** [comment]
It does get confusing!

I noticed with the Ant Design Datepicker, it's possible to use localization, 

Would it be a huge task to localize the date setting? Either globally or using the Country setting on an individual basis?

**Comment by dacronbb** [comment]
We ask that front end changes are not made without sign-off from design team (CBB or Lola)!

1) **I'd prefer it be localized if possible**, but I am on board with Andy's suggestion if not. While being _offended_ seems like overkill - I don't mind when Asian airlines ask me for day first, for example. :P

2) The instruction from JD was to include date, yes. People will just lie if they don't know - this is a COPPA thing, not a "we need your birthday to display it" thing.

3) I'm fine w/ First name and Last name as is - each field is optional :P 

4) I would expect the field to allow typing or selection via dropdown. Dunno, 1920 or so seems good :P

**Comment by domino14** [comment]
We looked at a number of different screenshots of different COPPA compliant sign up pages, and they all have MM - DD - YYYY. I think as long as they are three separate boxes, and not one single widget, it is fine. The backend would still save as YYYY-MM-DD. Would localization flip the order of the first two boxes?

e.g.

<img width="504" alt="Screen Shot 2021-05-14 at 1 23 45 PM" src="https://user-images.githubusercontent.com/585318/118306573-9e226080-b4b7-11eb-9ba5-ca3b44b55fbc.png">

Does this look different in SGP/UK?

**Comment by Jayem2k20** [comment]
This is UK

![Twitch](https://user-images.githubusercontent.com/83062931/118323368-6982c900-b4f8-11eb-8d2d-b027e2bcc819.png)

**Comment by andy-k** [comment]
sharing my localization code for whoever's implementing this:

```js
$ cat loc.js 
// 2006-01-02 (hi Golang), 2012-01-02, 2006-10-02, 2006-01-09 are Mondays.
// Returns [0, 1, 2] in some order where 0 = year, 1 = month, 2 = date.
const determineLocalDateSequence = () => {
  const fmt = new Intl.DateTimeFormat();
  const s1 = fmt.format(new Date(2006, 0, 2));
  const dist = (s2) => {
    const l = Math.min(s1.length, s2.length);
    for (let i = 0; i < l; ++i) if (s1[i] !== s2[i]) return i;
    return l;
  };
  return [
    dist(fmt.format(new Date(2012, 0, 2))) * 3,
    dist(fmt.format(new Date(2006, 9, 2))) * 3 + 1,
    dist(fmt.format(new Date(2006, 0, 9))) * 3 + 2,
  ]
    .sort((a, b) => (a < b ? -1 : 1))
    .map((x) => x % 3);
};

console.log(determineLocalDateSequence());
$ LANG=en-US node loc
[ 1, 2, 0 ]
$ LANG=en-GB node loc
[ 2, 1, 0 ]
$ LANG=ja-JP node loc
[ 0, 1, 2 ]
```

**Comment by domino14** [comment]
thanks Andy! closing
