### ISSUE TITLE
Should moving a blank tile display the blank slip?

### ISSUE THREAD

**Issue by ddugovic** [domino14/liwords#635]
As seen several minutes into https://www.youtube.com/watch?v=6NvD51CQ_7g ; sorry I lack a timestamp.

**Comment by andy-k** [comment]
need exact timestamp

**Comment by danibarker** [comment]
10:49

**Comment by domino14** [comment]
Conrad agreed that we don't need to do this. It makes it difficult to re-designate the blank, and now the annoyance of moving the blank tile is mitigated by the ability to flip two tiles on the board (by dragging them on each other).
