### ISSUE TITLE
the keyboard stops working sometimes to enter moves

### ISSUE THREAD

**Issue by domino14** [domino14/liwords#645]
About 28 minutes into axcertypo's Sun May 23 stream this can be seen.

I've also noticed it myself. I don't know what triggers it, but I have a feeling it may have to do with blindfold / TTS mode.

**Comment by andy-k** [comment]
link: https://www.twitch.tv/videos/1033171496?t=00h26m20s

at 27:14 it says "invalid command". so it's related to blindfold mode.

with blindfold mode enabled, `;` activates the blindfold mode invisible CLI.
`;` is easily typoed when typing `L` of `SILK`.

**Comment by domino14** [comment]
Thanks, good point. Maybe there should be some audio or visual indicator
that blindfold mode turned on.

**Comment by domino14** [comment]
this can go under blindfold improvements
