### ISSUE TITLE
Tournament spread cap

### ISSUE THREAD

**Issue by ddugovic** [domino14/liwords#686]
In [today's COSY tournament](https://woogles.io/tournament/COSY2021) the tournament organizer needs to manually overwrite scores in order to calculate tiebreaks correctly (accounting for randomness of pairings in the first rounds since there are some novice players).

Round 1 cap: 150 points
Round 2 cap: 200 points
etc.?

**Comment by domino14** [comment]
we've decided as a team that philosophically we just don't like spread caps, although we understand some directors like them. we will make it easier to override game results without actually overwriting the game.

**Comment by domino14** [comment]
i think we're ok with this now as long as it's an optional setting.

**Comment by domino14** [comment]
#1011

**Comment by ddugovic** [comment]
Thanks, I'll try to remember in the future to suggest potentially contentious ideas as options.

**Comment by domino14** [comment]
closed by #1011
