### ISSUE TITLE
wrong number of wins shown for person with previous bye

### ISSUE THREAD

**Issue by domino14** [domino14/liwords#791]
<img width="264" alt="Screen Shot 2021-08-07 at 12 03 45 PM" src="https://user-images.githubusercontent.com/585318/128606336-d6c3ad4a-ab63-4dc6-bc31-d1a1eaee1ae8.png">

GIJoel had a bye prior to tournament; Elfinmagic assigned herself a bye and paired him with the other missing player (SARANYA) .. GIJoel still shows as 1-0 even after refresh.

**Comment by domino14** [comment]
this fixes itself once a score comes in, but it appears to be a back-end bug.

**Comment by jvc56** [comment]
This was fixed by some PR and I forget to tag this.
