### ISSUE TITLE
Create Rules for Spread for tournament mode flagging

### ISSUE THREAD

**Issue by bnjy99** [domino14/liwords#840]
I believe the team all agreed that the following rule is appropriate to use for game spread when a player flags:

The game spread should be 50 plus the difference in score between the two players, with a minimum value of 50 (so if the player who flagged was leading, they would get a 50 point loss. If they were behind by 100 when they flagged, they would get a 150 point loss.)

**Comment by domino14** [comment]
this was implemented in #841
