### ISSUE TITLE
PostgreSQL database version

### ISSUE THREAD

**Issue by ddugovic** [domino14/liwords#849]
Apparently the postgres docker image is version 14, but the database was compiled using version 13?

```
$ docker-compose logs --tail=1
db_1           | 2021-10-02 01:18:07.407 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 13, which is not compatible with this version 14.0 (Debian 14.0-1.pgdg110+1).
```

**Comment by domino14** [comment]
we don't lock the database version anywhere, so maybe your pg docker image updated, but your data volume remained on the old version of pg?
