### ISSUE TITLE
You can build all the GUI with golang these days using GIOUI

### ISSUE THREAD

**Issue by gedw99** [domino14/liwords#854]
I found this repo cause i was checking out the use of nats and web sockets

I think that you woudl be interested in GIO

https://gioui.org/

https://github.com/gioui/gio-example

It compiles to GUI to wasm and nothing else. runs on web, desktop, mobile.

Here is a game that shows it off.
https://git.sr.ht/~whereswaldon/pointstar
- uses a web sockets to play a game
- make file makes it obvious.
just add a html frameset for 2 screens :)
``` 
<HTML>
    <HEAD>
    <TITLE> Frames for Game sim </TITLE>
    </HEAD>

    <FRAMESET ROWS="100%, *" COLS="*, 50%">
    <FRAME SRC="http://localhost:8080/" body bgcolor="#ffffcc">
    <FRAME SRC="http://localhost:8080/">
    </FRAMESET>

   </HTML> 
``` 

Many others are using this for games

Compilation to tinygo is currently broken... But not for long

Its also fast.... Ou wont need to use Rust to make fully wasm games.

RTL Text is being worked on in GIO. So it can do Arabic etc.

If you have any question the devs are here:
https://app.slack.com/client/T029RQSE6/CM87SNCGM

**Comment by gedw99** [comment]
Here is what https://git.sr.ht/~whereswaldon/pointstar looks like:

![Screenshot 2021-10-05 at 16 45 12](https://user-images.githubusercontent.com/53147028/136046221-ca2e6942-7bed-4dbc-8134-e24d23ab2244.png)

**Comment by gedw99** [comment]
Everything is embedded.

The images are Vectors. GIO can also use SVG.
there is no JS of course.

![Screenshot 2021-10-05 at 16 51 31](https://user-images.githubusercontent.com/53147028/136047272-3d014b2b-60aa-44e2-86cd-f9d43bddec5d.png)

**Comment by domino14** [comment]
thanks, but we have a pretty massive TypeScript / React frontend.
